[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_SUPABASE_URL = "https://yfosumpmtmcomfpbspaz.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlmb3N1bXBtdG1jb21mcGJzcGF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3MTU0NTMsImV4cCI6MjA4NTI5MTQ1M30.J5eEMRX_A6OnjAD08YIOT_Vk7TJqsQ_0YDGGRGebBrY"
  VITE_SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlmb3N1bXBtdG1jb21mcGJzcGF6Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2OTcxNTQ1MywiZXhwIjoyMDg1MjkxNDUzfQ.3nDEA7aPQ7HVs1w7xcoFMMzZ3_cpz30_5YA-RcrnInc"
  VITE_GEMINI_API_KEY = "AIzaSyCbI-XA4Ep3pQzVXXbeUEyA6qMOPZKPAqQ"

# Redirige todas las rutas al index.html para que React Router funcione
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
